language: generic
sudo: required
services:
  - docker
  
before_install:
  - docker build -t a7modkrishna/frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true a7modkrishna/frontend npm run test
  